---
# Run PowerShell commands
- name: Get Windows version
  win_shell: |
    Get-CimInstance Win32_OperatingSystem | Select-Object Caption, Version
  register: os_info

- name: Run a command
  win_command: hostname
