---
- name: Configure Windows Web Server
  hosts: all
  gather_facts: true

  tasks:

    - name: Install IIS
      win_feature:
        name: Web-Server
        state: present
        include_management_tools: yes

    - name: Ensure IIS service is running
      win_service:
        name: W3SVC
        state: started

    - name: Benchmark - Run 100 commands
      win_shell: Get-Date
      loop: "{{ range(1,100) }}"