name: Ansible Deploy

on:
  workflow_dispatch:
    inputs:
      inventory:
        description: 'Inventory path (e.g. inventories/staging/hosts.yml)'
        required: true
        default: 'inventories/qa/hosts.yml'
      playbook:
        description: 'Playbook name (e.g. deploy.yml)'
        required: true
        default: 'deploy.yml'

jobs:
  ansible:
    name: Run Ansible
    runs-on: ubuntu-latest

    container:
      image: alpine/ansible:2.20.0

    env:
      ANSIBLE_HOST_KEY_CHECKING: "False"
      ANSIBLE_USER: ${{ secrets.ANSIBLE_USER }}
      ANSIBLE_PASSWORD: ${{ secrets.ANSIBLE_PASSWORD }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install sshpass
        run: apk add --no-cache sshpass

      - name: Verify sshpass
        run: |
          which sshpass
          sshpass -V

      - name: Run Playbook
        run: |
          ansible-playbook \
            -i "${{ github.event.inputs.inventory }}" \
            "playbooks/${{ github.event.inputs.playbook }}" \
            -e ansible_user="$ANSIBLE_USER" \
            -e ansible_password="$ANSIBLE_PASSWORD" \
            -e ansible_become_password="$ANSIBLE_PASSWORD" \
            -e ansible_connection=ssh \
            -e ansible_ssh_common_args="-o StrictHostKeyChecking=no -o PreferredAuthentications=password -o PubkeyAuthentication=no" \
            -vv