name: Ansible Deploy

on:
  workflow_dispatch:
    inputs:
      inventory:
        description: 'Inventory path (e.g. inventories/staging/hosts)'
        required: true
        default: 'inventories/qa'
      playbook:
        description: 'Playbook name (e.g. deploy.yml)'
        required: true
        default: 'deploy.yml'

jobs:
  ansible:
    name: Run Ansible
    runs-on: ubuntu-latest
    container:
      image: alpine/ansible:2.20.0

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install sshpass
        run: apk add --no-cache sshpass        # alpine based image hai
      
      # - name: Debug sshpass
      #   run: |
      #     which sshpass
      #     sshpass -V
      #     echo "Testing SSH connection..."
      #     sshpass -p '${{ secrets.ANSIBLE_PASSWORD }}' ssh -o StrictHostKeyChecking=no -o PreferredAuthentications=password ${{ secrets.ANSIBLE_USER }}@20.164.208.6 echo "connected"

      - name: Run Playbook
        run: |
          ansible-playbook \
            -i ${{ github.event.inputs.inventory }} \
            playbooks/${{ github.event.inputs.playbook }} \
            --extra-vars "ansible_user=${{ secrets.ANSIBLE_USER }} ansible_password=${{ secrets.ANSIBLE_PASSWORD }} ansible_become_password=${{ secrets.ANSIBLE_PASSWORD }}" \
            -v